name: Linux
on:
  push:
    branches-ignore:
      - '**/sources/**'
      - '**/windows/**'
      - '**/macos/**'
    paths-ignore:
      - '.github/workflows/sources.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
      - 'data/artwork/**'
      - 'data/packaging/macos/**'
      - 'data/packaging/windows/**'
      - 'data/platform/macos/**'
      - 'data/platform/windows/**'
      - 'docs/**'
      - '.clang-format'
      - '.git-blame-ignore-revs'
      - '.git-properties'
      - 'Changelog.txt'
      - 'LICENSE'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/sources.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
      - 'data/artwork/**'
      - 'data/packaging/macos/**'
      - 'data/packaging/windows/**'
      - 'data/platform/macos/**'
      - 'data/platform/windows/**'
      - 'docs/**'
      - '.clang-format'
      - '.git-blame-ignore-revs'
      - '.git-properties'
      - 'Changelog.txt'
      - 'LICENSE'
      - '**.md'

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, '/debian/') }}
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        submodules: true
    - name: Check for Docker
      run: |
        (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
        id
        ls -la ${GITHUB_WORKSPACE}
        git config --system -l
        git config --global -l
    - name: Fetch tags
      run: |
        git fetch --prune --depth=1 --no-recurse-submodules
    - name: Parse project data
      run: |
        echo "project_version=`sed -n -E -e "/^project\(wxFormBuilder[[:space:]]+VERSION[[:space:]]+(.*)[[:space:]]+LANGUAGES.*$/{s//-\1/p;q}" CMakeLists.txt `" >> $GITHUB_ENV
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        arch: x86_64
        bundle: wxFormBuilder${{ env.project_version }}.flatpak
        manifest-path: data/packaging/linux/flatpak/org.wxformbuilder.wxFormBuilder.json
        cache-key: flatpak-builder-${{ github.sha }}
  debian:
    name: Debian Package
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, '/flatpak/') }}
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        submodules: true
    - name: Fetch tags
      run: |
        git fetch --prune --depth=1 --no-recurse-submodules
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install libwxgtk3.0-gtk3-dev libwxgtk-media3.0-gtk3-dev libboost-dev debhelper fakeroot rename xvfb
    - name: Setup package build
      run: |
        cp -rf data/packaging/linux/debian/ ./debian/
        echo "package_basedir=${GITHUB_WORKSPACE%/*}" >> $GITHUB_ENV
    - name: Build package
      run: |
        dpkg-buildpackage --build=binary --no-sign --root-command=fakeroot --jobs=auto
        rename "s/(.+_.+_)(.*)/\$1ubuntu-`lsb_release -r -s`_\$2/" "${{ env.package_basedir }}/"*.deb
    - name: Test package
      run: |
        xvfb-run --server-args="-screen 0, 1280x720x24" -a debian/wxformbuilder/usr/bin/wxformbuilder -v
        xvfb-run --server-args="-screen 0, 1280x720x24" -a debian/wxformbuilder/usr/bin/wxformbuilder -g test/wxfbTest.fbp
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: Debian Package
        path: |
          ${{ env.package_basedir }}/*.deb
